"""empty message

Revision ID: 2cec11982f6a
Revises: df750288ca5a
Create Date: 2022-11-18 15:30:13.566795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cec11982f6a'
down_revision = 'df750288ca5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('services', sa.Column('modified', sa.DateTime(), nullable=True))
    op.drop_column('services', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_column('services', 'modified')
    op.drop_column('services', 'created')
    # ### end Alembic commands ###
